### ISSUE TITLE
Deprecated repo ?

### ISSUE THREAD

**Issue by kuuak** [superhuit-ch/generator-fractal-component#11]
Hey @luisbraga & @hsmio should archive this repo ? 

I keep receiving security alert notification about this repo, and as I think we will not use this tool anymore, it could be good to archive it.

<img width="630" alt="Capture d’écran 2021-09-22 à 11 22 54" src="https://user-images.githubusercontent.com/6989959/134318008-58d50764-7a5e-4a2c-a22a-eeef449f3384.png">

**Comment by hsmio** [comment]
Sure!
